- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create Instance
      ganeti.cli.gnt_instance:
        name: test
        state: present
        params:
          disk_template: file
          disks:
            - size: 10G
          os_type: noop
          name_check: False
          ip_check: False
          nics:
            - name: test
              link: br_gnt
              mode: bridged
