- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create Instance
      ganeti.cli.gnt_instance:
        name: test
        state: present
        params:
          disk-template: file
          disk:
            - size: 10G
          os-type: noop
          name-check: False
          ip-check: False
          hypervisor: fake
          net:
            - name: test
              link: br_gnt
              mode: bridged
              vlan: 50
            - name: test2
              link: br_gnt
            - name: test3
              link: br_gnt
              vlan: 200
